# .github/labels.yml

# GitHub Default Labels
- name: "fix"
  color: "d73a4a"
  description: "Something isn't working"
- name: "docs"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "feat"
  color: "a2eeef"
  description: "New feature or request"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

# Critical Production Labels
- name: "critical"
  color: "ff0000"
  description: "🔥 Critical production issue requiring urgent attention"
- name: "automated"
  color: "0052cc"
  description: "Automated pull request"
- name: "release"
  color: "00ff00"
  description: "Release related changes"

  # Triage Label
- name: "needs-triage"
  color: "fbca04"
  description: "Needs triage to determine priority or classification"
