# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main # our main branch
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      issues: write # This is important for label creation
      contents: write # This is crucial for creating branches and committing changes
      pull-requests: write # This is crucial for creating and updating PRs
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_url: ${{ steps.release.outputs.release_url }}
      prerelease: ${{ steps.release.outputs.prerelease }}
      id: ${{ steps.release.outputs.id }}
      body: ${{ steps.release.outputs.body }}
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: main
###
### Give Release-please permission
### Go to your GitHub repository.
### Click on Settings.
### In the left sidebar, click on Actions.
### Then click on General.
### Scroll down to "Workflow permissions".
### Set the default permissions granted to the GITHUB_TOKEN for all workflow runs.
### [ ] Read repository contents and packages permissions
### [x] Read and write permissions  <-- Make sure this is checked

### [x] Allow GitHub Actions to create and approve pull requests <-- You already checked this
